# Generated by Django 6.0.3 on 2026-05-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationerror',
            name='raw_data',
            field=models.TextField(db_index=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='original_file',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='parameter',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='sim_time',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='value',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='simulationsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='simulationsession',
            name='source_path',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='setting_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='setting_value',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='validationerror',
            name='error_details',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='validationerror',
            name='file_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
